require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'StrongboxReactNative' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/AdMob'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'StrongboxReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'StrongboxReactNative-tvOS' do
  # Pods for StrongboxReactNative-tvOS

  target 'StrongboxReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
